### Listar todos os dados ambientais
GET http://localhost:8080/api/dados-ambientais
Accept: application/json

### Listar todos os sensores
GET http://localhost:8080/api/sensores
Accept: application/json

### Listar todos os usuarios
GET http://localhost:8080/api/usuarios
Accept: application/json

### Adicionar novo usuario
POST http://localhost:8080/api/usuarios
Content-Type: application/json

{
      "nome": "Nome",
      "email": "email@email.com",
      "senha": "123456"
}

### Adicionar novos sensores
POST http://localhost:8080/api/sensores
Content-Type: application/json

{
      "tipos": 10,
      "localizacao": "Laguna"
}

### Cadastra um sensor para um usuario
POST http://localhost:8080/api/usuarios/1/register-sensor/1

### Adicionar novos dados ambientais
POST http://localhost:8080/api/sensores/1/colect-data?tipoDado=UMIDADE&valor=20
Content-Type: application/json

### Listar todos os sensores de um usuario
GET http://localhost:8080/api/usuarios/1/sensors
Accept: application/json

### Listar todos os dados ambientais de um sensor
GET http://localhost:8080/api/usuarios/1/search-by-sensor/1
Accept: application/json

### Reseta a base de dados - dados ambientais
DELETE http://localhost:8080/api/dados-ambientais/reset

### Reseta a base de dados - sensores
DELETE http://localhost:8080/api/sensores/reset

### Reseta a base de dados - usuarios
DELETE http://localhost:8080/api/usuarios/reset

### Ajuda
GET http://localhost:8080/api/usuarios/ajuda